name: Android device
description: Suggest settings for an Android device
title: "[Android] "
labels:
  - android
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I will only use English
          required: true
        - label: I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud-devices/issues?q=is%3Aissue) to see if someone else has already submitted the same device
          required: true
  - type: input
    id: device_name
    attributes:
      label: "Device name"
      description: "Full name of the device (manufacturer and model name)"
      placeholder: "e.g., Google Pixel 8"
    validations:
      required: true
  - type: textarea
    id: debug-info
    attributes:
      label: "Debug info"
      description: |
        1. Open the Better xCloud app
        2. Open script settings
        3. Scroll to the bottom, click on the "DEBUG INFO" button
        4. Click on the info box to copy the content to clipboard
        5. Paste that info into the input box below
        6. If you're on Android TV, you can take photos and upload them instead
    validations:
      required: true
  - type: input
    id: webview
    attributes:
      label: "WebView"
      description: "Which WebView are you using?"
      placeholder: "System/Thorium/Mulch"
    validations:
      required: true
  - type: checkboxes
    id: app_settings
    attributes:
      label: App settings
      description: Check which app settings you're using
      options:
        - label: Hardware Back button as Xbox button
          required: false
        - label: Optimize WebView performance
          required: false
